### ISSUE TITLE
Problem when deploying portlet (table pg_class)

### ISSUE THREAD

**Issue by anthonycharles** [rotterdam-cs/rcsnewsletter#16]
Hi,

I'm interested in using the rcs newsletter portlet. I tried to deploy it in my development environment and I get this strange error :  com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'bdd_liferay.pg_class' doesn't exist (Full stacktrace below).

I have tried on Liferay 6.1.0 with MySQL and also on Liferay 6.1.1 with Hypersonic with rcs-newsletter-portlet-2.1.3 and rcs-newsletter-portlet-2.1.4.

Do you have encounter this problem?

Anthony

Stacktrace with MySQL on Liferay 6.1.0 : 
14:42:10,573 ERROR [ContextLoader:220] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean wit
h name 'sessionFactory' defined in ServletContext resource [/WEB-INF/liferay-per
sistence.xml]: Invocation of init method failed; nested exception is org.springf
ramework.jdbc.BadSqlGrammarException: Hibernate-related JDBC operation; bad SQL
grammar []; nested exception is com.mysql.jdbc.exceptions.MySQLSyntaxErrorExcept
ion: Table 'inpes_liferay.pg_class' doesn't exist
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:288)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:190)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:563)
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:895)
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:425)
        at org.springframework.web.context.ContextLoader.createWebApplicationCon
text(ContextLoader.java:276)
        at org.springframework.web.context.ContextLoader.initWebApplicationConte
xt(ContextLoader.java:197)
        at org.springframework.web.context.ContextLoaderListener.contextInitiali
zed(ContextLoaderListener.java:47)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContex
t.java:4765)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContex
t.java:5260)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase
.java:866)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:84
2)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)

```
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.jav
```

a:1095)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig
.java:1617)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:44
1)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: org.springframework.jdbc.BadSqlGrammarException: Hibernate-related JD
BC operation; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.
MySQLSyntaxErrorException: Table 'inpes_liferay.pg_class' doesn't exist
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.d
oTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslat
or.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.orm.hibernate3.HibernateAccessor.convertJdbcAcces
sException(HibernateAccessor.java:442)
        at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(Hibern
ateTemplate.java:414)
        at org.springframework.orm.hibernate3.HibernateTemplate.execute(Hibernat
eTemplate.java:339)
        at org.springframework.orm.hibernate3.LocalSessionFactoryBean.updateData
baseSchema(LocalSessionFactoryBean.java:935)
        at org.springframework.orm.hibernate3.LocalSessionFactoryBean.afterSessi
onFactoryCreation(LocalSessionFactoryBean.java:883)
        at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPr
opertiesSet(AbstractSessionFactoryBean.java:213)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
        ... 26 more
Caused by: com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'inpes_lif
eray.pg_class' doesn't exist
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
        at com.mysql.jdbc.Connection.execSQL(Connection.java:3250)
        at com.mysql.jdbc.Connection.execSQL(Connection.java:3179)
        at com.mysql.jdbc.Statement.executeQuery(Statement.java:1207)
        at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyState
ment.java:35)
        at org.hibernate.tool.hbm2ddl.DatabaseMetadata.initSequences(DatabaseMet
adata.java:151)
        at org.hibernate.tool.hbm2ddl.DatabaseMetadata.<init>(DatabaseMetadata.j
ava:69)
        at org.hibernate.tool.hbm2ddl.DatabaseMetadata.<init>(DatabaseMetadata.j
ava:62)
        at org.springframework.orm.hibernate3.LocalSessionFactoryBean$1.doInHibe
rnate(LocalSessionFactoryBean.java:940)
        at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(Hibern
ateTemplate.java:406)
        ... 32 more

**Comment by gustavogenovese** [comment]
That is because RCS newsletter portlet uses PostgreSQL by default. Please read the manual on how to make it work with MySQL

**Comment by anthonycharles** [comment]
Ok I had opened the wrong user guide...
Thanks a lot for the quick answer and sorry for the stupid question.

Anthony
