### ISSUE TITLE
Problem in Send Newsletter

### ISSUE THREAD

**Issue by developera** [rotterdam-cs/rcsnewsletter#22]
Hello,

I am using Liferay CE 6.1.0 y GA1 and the RCS-Newsletter Portlet version 2.1.4. Portlet is working properly except when I "Send Newsletter" that I get this exception. In the Archive tab the Archive Email Preview is correct too.

12:03:09,856 ERROR [NewsletterMailingServiceImpl:112] Error while trying to read
 article
java.lang.NullPointerException
        at com.rcs.newsletter.core.service.util.EmailFormat.getEmailFromTemplate
(EmailFormat.java:340)
        at com.rcs.newsletter.core.service.NewsletterMailingServiceImpl.sendMail
ing(NewsletterMailingServiceImpl.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflecti
on(AopUtils.java:309)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJo
inpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor.in
voke(TransactionInterceptor.java:110)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(
AsyncExecutionInterceptor.java:80)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)

Please, could you give me any idea to solve this issue?.

Thanks in advance.

**Comment by developera** [comment]
I have solved. It just needed to define the Category newsletter.

**Comment by falaufer** [comment]
Great!

Fabiana J. Laufer
Computer Engineer

Rotterdam Community Solutions BV
Schiehavenkade 68
3024 EZ Rotterdam
+3188 7326 010 | +3188 7326 001
fabiana@rotterdam-cs.com
www.rotterdam-cs.com

2013/4/11 Miguel Angel Lopera notifications@github.com

**Comment by gabriel1979** [comment]
Hi! I have the same problem but in my case, I have the newsletter category created and added. Which could be the problem?

Thanks in advance!
