### ISSUE TITLE
Exception thrown when loading the Newsletter Administration

### ISSUE THREAD

**Issue by maberastain** [rotterdam-cs/rcsnewsletter#3]
An exception is thrown when loading the Newsletter Administration for the first time.
The exception is:

Sass::SyntaxError: Invalid CSS after "...ke_icon{filter:": expected expression (e.g. 1px, bold), was ";}.cke_skin_kam..." 
                expected at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:897
               expected! at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/script/lexer.rb:193
             assert_expr at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/script/parser.rb:443
                   parse at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/script/parser.rb:49
                    send at org/jruby/RubyKernel.java:2092
             sass_script at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:788
                  value! at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:662
             declaration at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:639
  declaration_or_ruleset at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:408
                    call at org/jruby/RubyProc.java:274
                    call at org/jruby/RubyProc.java:229
                 rethrow at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:872
  declaration_or_ruleset at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:418
             block_child at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:380
          block_contents at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:369
                   block at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:361
                 ruleset at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:355
             block_child at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:379
          block_contents at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:372
              stylesheet at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:57
                   parse at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/scss/parser.rb:26
                _to_tree at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/engine.rb:320
                 _render at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/engine.rb:293
                  render at file:/opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/ROOT/WEB-INF/lib/ruby-gems.jar!/gems/sass-3.1.7/lib/sass/engine.rb:240
                  (root) at <script>:38
14:42:27,222 ERROR [MinifierFilter:421] Unable to parse SASS on CSS /opt/liferay/newsletter61/liferay-portal-6.1.0-ce-ga1/tomcat-7.0.23/webapps/rcs-newsletter-portlet/js/ckeditor/skins/kama/editor.css
org.jruby.embed.EvalFailedException: (SyntaxError) Invalid CSS after "...ke_icon{filter:": expected expression (e.g. 1px, bold), was ";}.cke_skin_kam..." 
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:127)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1231)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1224)
        at com.liferay.portal.scripting.ruby.RubyExecutor.eval(RubyExecutor.java:148)
        at com.liferay.portal.scripting.ruby.RubyExecutor.eval(RubyExecutor.java:105)
        at com.liferay.portal.servlet.filters.dynamiccss.DynamicCSSUtil._parseSass(DynamicCSSUtil.java:295)
        at com.liferay.portal.servlet.filters.dynamiccss.DynamicCSSUtil.parseSass(DynamicCSSUtil.java:138)
        at com.liferay.portal.servlet.filters.minifier.MinifierFilter.minifyCss(MinifierFilter.java:418)
        at com.liferay.portal.servlet.filters.minifier.MinifierFilter.minifyCss(MinifierFilter.java:410)
        at com.liferay.portal.servlet.filters.minifier.MinifierFilter.getMinifiedContent(MinifierFilter.java:348)
        at com.liferay.portal.servlet.filters.minifier.MinifierFilter.processFilter(MinifierFilter.java:459)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at com.liferay.portal.kernel.servlet.PortalClassLoaderFilter.doFilter(PortalClassLoaderFilter.java:69)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at sun.reflect.GeneratedMethodAccessor490.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:54)
        at $Proxy570.doFilter(Unknown Source)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:72)
at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:121)
        at com.liferay.portal.servlet.filters.gzip.GZipFilter.processFilter(GZipFilter.java:123)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at com.liferay.portal.kernel.servlet.PortalClassLoaderFilter.doFilter(PortalClassLoaderFilter.java:69)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at sun.reflect.GeneratedMethodAccessor490.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:54)
        at $Proxy570.doFilter(Unknown Source)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:72)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:121)
        at com.liferay.portal.servlet.filters.cache.CacheFilter.processFilter(CacheFilter.java:414)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at com.liferay.portal.kernel.servlet.PortalClassLoaderFilter.doFilter(PortalClassLoaderFilter.java:69)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at sun.reflect.GeneratedMethodAccessor490.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:54)
        at $Proxy570.doFilter(Unknown Source)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:72)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:121)
        at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:55)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at com.liferay.portal.kernel.servlet.PortalClassLoaderFilter.doFilter(PortalClassLoaderFilter.java:69)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at sun.reflect.GeneratedMethodAccessor490.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:54)
        at $Proxy570.doFilter(Unknown Source)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:72)
        at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:121)
        at com.liferay.portal.servlet.filters.header.HeaderFilter.processFilter(HeaderFilter.java:150)
        at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at com.liferay.portal.kernel.servlet.PortalClassLoaderFilter.doFilter(PortalClassLoaderFilter.java:69)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:203)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:105)
        at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:70)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
Caused by: org.jruby.exceptions.RaiseException: (SyntaxError) Invalid CSS after "...ke_icon{filter:": expected expression (e.g. 1px, bold), was ";}.cke_skin_kam..." 

Found on LR 6.1 & newsletter version 2.1.4

**Comment by alvartaco** [comment]
It was fixed following:

It will be available in portlet version 2.1.5

Alejandro

**Comment by alvartaco** [comment]
Fixed files are available to be downloaded from here.

Enjoy!

**Comment by alvartaco** [comment]
Status moved to RESOLVED
